### ISSUE TITLE
error:connect failed, check network status.

### ISSUE THREAD

**Issue by happyeddie** [gyh1621/GetSubtitles#10]
F:\TvSeries\Marvel's Agents of S.H.I.E.L.D\Season 5>getsub ./ --debug

├ Marvel's.Agents.of.S.H.I.E.L.D.S05E11.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvel's.Agents.of.S.H.I.E.L.D.S05E12.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvel's.Agents.of.S.H.I.E.L.D.S05E13.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvel's.Agents.of.S.H.I.E.L.D.S05E14.1080p.REPACK.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E02.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E03.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E04.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E05.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E06.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E07.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E08.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E09.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E10.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
├ ./
├
├ error:connect failed, check network status.

├ Marvels.Agents.of.S.H.I.E.L.D.S05E15.720p.HDTV.x264-AVS.mkv
├ ./
├
├ error:unknown error. try again.

===============================FAILED LIST===============================

 1. name: Marvel's.Agents.of.S.H.I.E.L.D.S05E11.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
 2. name: Marvel's.Agents.of.S.H.I.E.L.D.S05E12.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
 3. name: Marvel's.Agents.of.S.H.I.E.L.D.S05E13.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
 4. name: Marvel's.Agents.of.S.H.I.E.L.D.S05E14.1080p.REPACK.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
 5. name: Marvels.Agents.of.S.H.I.E.L.D.S05E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
 6. name: Marvels.Agents.of.S.H.I.E.L.D.S05E02.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
 7. name: Marvels.Agents.of.S.H.I.E.L.D.S05E03.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
 8. name: Marvels.Agents.of.S.H.I.E.L.D.S05E04.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
 9. name: Marvels.Agents.of.S.H.I.E.L.D.S05E05.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
10. name: Marvels.Agents.of.S.H.I.E.L.D.S05E06.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
11. name: Marvels.Agents.of.S.H.I.E.L.D.S05E07.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
12. name: Marvels.Agents.of.S.H.I.E.L.D.S05E08.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
13. name: Marvels.Agents.of.S.H.I.E.L.D.S05E09.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
14. name: Marvels.Agents.of.S.H.I.E.L.D.S05E10.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv
    path: ./
    info: connect failed, check network status.
    TRACE_BACK:
15. name: Marvels.Agents.of.S.H.I.E.L.D.S05E15.720p.HDTV.x264-AVS.mkv
    path: ./
    info: unknown error. try again.
    TRACE_BACK: Traceback (most recent call last):
  File "d:\program-files\python36\lib\site-packages\main.py", line 438, in start
    downloader.get_subtitles(tuple(keywords))
  File "d:\program-files\python36\lib\site-packages\zimuzu.py", line 46, in get_subtitles
    tab_text = bs_obj.find('div', {'class': 'article-tab'}).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by raawaa** [comment]
遇到同样的错误

**Comment by gyh1621** [comment]
我这里尝试了下是 zimuku 下载器出问题了，但是 subhd 和 zimuzu 没问题，可以用 getsub ./ --downloader zimuzu 指定下载器试一下。
connect error 是请求网站超时了，这里有个 bug 就是一个下载器超时并不会自动切换到下一个下载器。
这两个问题我后面看下，可以先指定下载器使用。

**Comment by gyh1621** [comment]
已解决，新版本会跳过超时的下载器

**Comment by gyh1621** [comment]
已解决，新版本会跳过超时的下载器
