### ISSUE TITLE
下载出错，保存的文件为0大小

### ISSUE THREAD

**Issue by zasl** [gyh1621/GetSubtitles#14]
├ Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG.mp4
├ E:\Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG
├
├   1) 【简】【繁】【英】【双】  [SUBHD]黑豹.Black.Panther.2018.1080p.BluRay.Orange字幕组&远鉴字幕组
├   2) 【简】      【英】【双】  [SUBHD][黑豹].Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG
├   3) 【简】      【英】【双】  [SUBHD]【远鉴字幕组&Orange字幕组】黑豹【蓝光版特效中英双字】[email protected]
├   4) 【简】            【双】  [SUBHD]【远鉴字幕组&Orange字幕组】黑豹 Black.Panther.2018.1080p.BluRay.x264-SPARKS @CHDbits
├   5)       【繁】              [SUBHD]黑豹 Black Panther
├
├  choose subtitle: 3
├
├ Get '[SUBHD]【远鉴字幕组&Orange字幕组】黑豹【蓝光版特效中英双字】[email protected]'...  100.00%
├ error:Unrar not installed?add --debug to get more info of the error

===============================FAILED LIST===============================

 1. name: Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG.mp4
    path: E:\Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG
    info: Unrar not installed?add --debug to get more info of the error

total: 1  success: 0  fail:

getsub E:\aria2down\Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG\Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG.mp4 -d subhd -q

├ Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG.mp4
├ E:\aria2down\Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG
├
├   1) 【简】【繁】【英】【双】  [SUBHD]黑豹.Black.Panther.2018.1080p.BluRay.Orange字幕组&远鉴字幕组
├   2) 【简】      【英】【双】  [SUBHD][黑豹].Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG
├   3) 【简】      【英】【双】  [SUBHD]【远鉴字幕组&Orange字幕组】黑豹【蓝光版特效中英双字】[email protected]
├   4) 【简】            【双】  [SUBHD]【远鉴字幕组&Orange字幕组】黑豹 Black.Panther.2018.1080p.BluRay.x264-SPARKS @CHDbits
├   5)       【繁】              [SUBHD]黑豹 Black Panther
├
├  choose subtitle: 2
├
├ Get '[SUBHD][黑豹].Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG'...  100.00%
├ error:max() arg is an empty sequence. add --debug to get more info of the error

===============================FAILED LIST===============================

 1. name: Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG.mp4
    path: E:\Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG
    info: max() arg is an empty sequence. add --debug to get more info of the error

total: 1  success: 0  fail: 1

win10 python3.6，其他py程序正常，比如网易音乐那些的。求解
用-D -Q参数指定也是这样

**Comment by gyh1621** [comment]
第一个错误提示里写着了找不到unrar，win下的unrar设置可以看下这个issue [提示未安装unrar](https://github.com/gyh1621/GetSubtitles/issues/2)。
第二个是字幕包的问题，字幕包里面没有字幕：
$ getsub Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG.mp4 -d subhd -q -s --debug
├ Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG.mp4
├ /home/gyh
├
├   1) 【简】【繁】【英】【双】  [SUBHD]黑豹.Black.Panther.2018.1080p.BluRay.Orange字幕组&远鉴字幕组
├   2) 【简】      【英】【双】  [SUBHD][黑豹].Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG
├   3) 【简】      【英】【双】  [SUBHD]【远鉴字幕组&Orange字幕组】黑豹【蓝光版特效中英双字】[email protected]
├   4) 【简】            【双】  [SUBHD]【远鉴字幕组&Orange字幕组】黑豹 Black.Panther.2018.1080p.BluRay.x264-SPARKS @CHDbits
├   5)       【繁】              [SUBHD]黑豹 Black Panther
├
├  choose subtitle: 2
├ 
├ Get '[SUBHD][黑豹].Black.Panther.2018.1080p.BluRay.H264.AAC-RARBG'...  100.00%
├
├
├  choose subtitle: ^CTraceback (most recent call last):

**Comment by gyh1621** [comment]
上字幕网站看了下那个字幕包，大小是0K，下载后解压是一个txt，里面是实际字幕包的网盘地址 
 :disappointed_relieved: 
![image](https://user-images.githubusercontent.com/17004041/40953933-a969dc22-68b4-11e8-937a-8f05418de792.png)
