### ISSUE TITLE
是否考虑同时下载多个字幕

### ISSUE THREAD

**Issue by zscorpio** [gyh1621/GetSubtitles#16]
是否考虑同时下载多个字幕,比如2-3个同时保存,现在好像字幕后缀没有标记字幕语言,比如chs之类?
多字幕主要原因是考虑 可能1个字幕的时间轴有问题,也许另外一个是好的
以及比如2个格式,srt和ass,有的不支持ass后缀

**Comment by gyh1621** [comment]
恩，多字幕和同时保存两个格式确实可以做下。
但多字幕可能只能在查询模式里提供（比如一次选择多个候选项），因为自动模式下解压出的字幕是要保持和资源的同名因此只能同时存在一个结果字幕（如果那个压缩包里有srt和ass格式可以同时保存两个）。

还有上面说的字幕后缀没有标记字幕语言这个，说的是自动模式下保存的结果字幕吗？结果字幕会重命名为资源名，但是在 getsub 命令结束后会显示自动选择的原始字幕名。

**Comment by zscorpio** [comment]
恩,多字幕好像同一后缀,下多个意义的确没有那么大,2个后缀可以留,不过可能是因为我plex有点怪,我支持的就是手动调整下时间轴.
后面那个字幕语言问题是这样的,
比如资源名叫I.Robot.2004.1080p.Bluray.x264.DTS-DEFiNiTE.mkv
那么字幕文件名好像是叫 I.Robot.2004.1080p.Bluray.x264.DTS-DEFiNiTE.srt
能不能命名为 I.Robot.2004.1080p.Bluray.x264.DTS-DEFiNiTE.chs.srt或者eng类似这种
加上语言,否则的话,好像播放器一般不能识别什么语言,会显示未知,不清楚别人有没有这种场景哈

**Comment by gyh1621** [comment]
字幕和资源同名是考虑播放器能自动加载字幕。
播放器不能识别语言这个有点奇怪，不过我没用过 plex，猜测是原始字幕文件编码的问题？你那边是改了字幕名字以后就能识别了吗？
我觉得这个有点偏，暂时可能不会做。

**Comment by zscorpio** [comment]
我可能说的不是很清楚
取个例子哈http://files.zmzjstu.com/ftp/2018/0619/47b65a8b6319167d408225a0286dd646.zip
http://zmz003.com/s/UVxd62 supergirl的字幕
里面包含了好多个文件
```
Supergirl.S03E23.720p.HDTV.x264-KILLERS.简体&英文.ass
Supergirl.S03E23.720p.HDTV.x264-KILLERS.繁体&英文.ass
Supergirl.S03E23.720p.HDTV.x264-KILLERS.简体&英文.srt
Supergirl.S03E23.720p.HDTV.x264-KILLERS.繁体&英文.srt
Supergirl.S03E23.720p.HDTV.x264-KILLERS.简体.ass
Supergirl.S03E23.720p.HDTV.x264-KILLERS.繁体.ass
Supergirl.S03E23.720p.HDTV.x264-KILLERS.简体.srt
Supergirl.S03E23.720p.HDTV.x264-KILLERS.繁体.srt
Supergirl.S03E23.720p.HDTV.x264-KILLERS.英文.srt
```
Supergirl.S03E23.720p.HDTV.x264-KILLERS这一块就是片名,然后后面还有一个"英文","简体&英文"类似这种,这样的话,播放器外挂字幕可以知道挂的是什么语言的字幕,否则的话,播放器应该不知道挂的是什么语言的字幕,但是更多的资料我暂时找不到了....
大概就是.chs.srt,.chs-eng.srt,类似这种.

**Comment by gyh1621** [comment]
前面你说的识别不了是播放器里面直接找不到这个字幕文件还是显示为乱码？

**Comment by zscorpio** [comment]
不是说识别不了,我那个是我plex问题,他识别不了ass(据说,但是我另外一个剧支持),所以想要srt字幕,这是需求来源哈哈
然后上面说的那个是播放不能识别字幕语言,就是有时候多个字幕语言,手动选择的时候,会看一下字幕语言类型,如果没有那个字幕语言,会显示位置,但是实际使用是正常的,无伤大雅

**Comment by zscorpio** [comment]
播放器那个我周末再试试,我多几个场景试试,到时候截图看看
也不是不重名原始字幕名,因为不重命名的话,理论上不会匹配当前文件名哈,等于说字幕挂不上去....需要重命名之后加语言

**Comment by zscorpio** [comment]
Deadpool.2.2018.UNRATED.iNTERNAL.1080p.BluRay.x264-SPRiNTER.chi.ass
Deadpool.2.2018.UNRATED.iNTERNAL.1080p.BluRay.x264-SPRiNTER.chs.srt
Deadpool.2.2018.UNRATED.iNTERNAL.1080p.BluRay.x264-SPRiNTER.mkv
Deadpool.2.2018.UNRATED.iNTERNAL.1080p.BluRay.x264-SPRiNTER.srt
Deadpool.2.2018.UNRATED.iNTERNAL.1080p.BluRay.x264-SPRiNTER.zh.srt
已经放弃了....每个播放器识别有点不太一样...
![1194052893181297810](https://user-images.githubusercontent.com/1071075/44328969-b2b3a480-a495-11e8-900a-087f087e2a6e.png)

**Comment by zongai** [comment]
我是用视频文件名和字幕版本名的相似度筛选，可以减少时间轴不匹配的情况。

**Comment by gyh1621** [comment]
前几天有点事耽搁了，刚刚更新上去了
添加 `-b` 参数同时保存 `.ass` 和 `.srt`
在 `-q` 模式下用 ',' 或 '，' 分隔选择多个字幕包下载，会将第一个字幕包中抽取的字幕重命名为视频名，后面的字幕包抽取的字幕按原名保存

**Comment by zscorpio** [comment]
辛苦辛苦了,谢谢!

**Comment by gyh1621** [comment]
有几个小bug，麻烦更新下

**Comment by gyh1621** [comment]
@zscorpio 我最近也开始用 plex 了，这次更新加了 `--plex` 参数，下载后的字幕能够加上 `.zh` 标识，这样跟你说的一样 plex 能识别为中文字幕。

**Comment by zscorpio** [comment]
@gyh1621 哈哈,好的,谢谢,那我去重新更新一遍字幕,不过我之前好像加.zh不行,不知道是不是姿势不对...

**Comment by gyh1621** [comment]
我前天跑了一遍，没有全部看 ，不过我看的几个视频里面中文都是识别的，就是你上面的 `Deadpool.2.2018.UNRATED.iNTERNAL.1080p.BluRay.x264-SPRiNTER.zh.srt` 这样的格式。你再试试hh

**Comment by zscorpio** [comment]
恩恩,好的,谢谢,晚上回家试试
