### ISSUE TITLE
debian下下载出错

### ISSUE THREAD

**Issue by firexbox** [gyh1621/GetSubtitles#17]
$ getsub -m Mr.Mercedes.S01E10.Jibber-Jibber.Chicken.Dinner.720p.DTV.WEB-DL.DD2.0.x264-NTb.mkv -q -s --debug

├  Mr.Mercedes.S01E10.Jibber-Jibber.Chicken.Dinner.720p.DTV.WEB-DL.DD2.0.x264-NTb.mkv
├  /home/cgq
├ 
├    1) 【简】【繁】【英】【双】  [ZMZ]Mr.Mercedes.S01E10.Jibber-Jibber.Chicken.Dinner.720p.DTV.WEB-DL.DD2.0.x264-NTb
├    2) 【简】【繁】【英】【双】  [ZMZ]Mr.Mercedes.S01E09.Ice.Cream.You.Scream.We.All.Scream.720p.DTV.WEB-DL.DD2.0.x264-NTb
├    3) 【简】【繁】【英】【双】  [ZMZ]Mr.Mercedes.S01E08.From.The.Ashes.720p.REPACK.DTV.WEB-DL.DD2.0.x264-NTb
├    4) 【简】【繁】【英】【双】  [ZMZ]Mr.Mercedes.S01E07.Willow.Lake.720p.DTV.WEB-DL.DD
├    5) 【简】【繁】【英】【双】  [ZMZ]Mr.Mercedes.S01E06.720p.WEBRip.x264-eSc
├ 
├   choose subtitle: 1
├  error:expected string or buffer. 

===============================FAILED LIST===============================

 1. name: Mr.Mercedes.S01E10.Jibber-Jibber.Chicken.Dinner.720p.DTV.WEB-DL.DD2.0.x264-NTb.mkv
    path: /home/cgq
    info: expected string or buffer. 
    TRACE_BACK: Traceback (most recent call last):
  File "/home/cgq/.local/lib/python2.7/site-packages/main.py", line 583, in start
    sub_choices = self.choose_subtitle(sub_dict)
  File "/home/cgq/.local/lib/python2.7/site-packages/main.py", line 207, in choose_subtitle
    choices = [int(c) for c in re.split(',|，', choices)]
  File "/usr/lib/python2.7/re.py", line 171, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or buffer

total: 1  success: 0  fail: 1

**Comment by gyh1621** [comment]
这个版本忘了测试py2，稍等

**Comment by gyh1621** [comment]
已更新
