### ISSUE TITLE
macOS 10.14，下载时报错

### ISSUE THREAD

**Issue by terryops** [gyh1621/GetSubtitles#19]
显示：
Get '[ZMZ]bojack.horseman.s05e01.720p.web...'...  100.00%
Error:Failed the read enough data

**Comment by gyh1621** [comment]
贴一下调用命令以及 getsub 的版本（`getsub -h`）

**Comment by terryops** [comment]
sudo getsub /Users/Terrygu/Downloads/Boardwalk.Empire.S01.1080p.BluRay.X264-BiRDHOUSE\[rartv\]/Boardwalk.Empire.S01E09.1080p.BluRay.X264-BiRDHOUSE.mkv  --debug
Password:

├  Boardwalk.Empire.S01E09.1080p.BluRay.X264-BiRDHOUSE.mkv
├  /Users/Terrygu/Downloads/Boardwalk.Empire.S01.1080p.BluRay.X264-BiRDHOUSE[rartv]
├
├  error:unknown error. try again.

===============================FAILED LIST===============================

 1. name: Boardwalk.Empire.S01E09.1080p.BluRay.X264-BiRDHOUSE.mkv
    path: /Users/Terrygu/Downloads/Boardwalk.Empire.S01.1080p.BluRay.X264-BiRDHOUSE[rartv]
    info: unknown error. try again.
    TRACE_BACK: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/getsub/main.py", line 615, in start
    sub_choice, link, session, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/getsub/main.py", line 501, in process_archive
    sub_choice, link
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/getsub/zimuzu.py", line 94, in download_file
    a = bs_obj.find('div', {'class': 'download-box'}).a
AttributeError: 'NoneType' object has no attribute 'a'


total: 1  success: 0  fail: 1

**Comment by terryops** [comment]
getsub 1.6.8.1

**Comment by gyh1621** [comment]
谢谢 会尽快修复的
2018年10月12日 +0800 PM2:02 terryops <notifications@github.com>，写道：

**Comment by terryops** [comment]
谢谢你才对。

**Comment by gyh1621** [comment]
不好意思这么晚才去看。我刚刚试了下，没有发现出错，不知道你那边后面还发生过这种情况吗

**Comment by terryops** [comment]
一样的。问题照常。

**Comment by gyh1621** [comment]
最新版本里我用zimuzu试了下还是没出错，我没有macOS环境也测试不了... 我把subhd加了回去，可以用subhd试试。
