### ISSUE TITLE
提示未安装unrar

### ISSUE THREAD

**Issue by lenhoo** [gyh1621/GetSubtitles#2]
` info: Unrar not installed?`
但是已经安装了

**Comment by gyh1621** [comment]
什么系统

**Comment by lenhoo** [comment]
windows 10

**Comment by fireflycao** [comment]
windows 10 
Get '[ZMZ]Narcos.S03E04.Checkmate.720p.NF.WEB-DL.DD5.1.x264-NTb'...  100.00%
├ error:Unrar not installed?

===============================FAILED LIST===============================

 1. name: Narcos.S03E04.Checkmate.1080p.NF.WEB-DL.DD5.1.x264-NTb.mkv
    path: Z:\Media\TV\Narcos.S03.1080p.NF.WEB.DD5.1.x264-NTb[rartv]
    info: Unrar not installed?
    TRACE_BACK:

total: 1  success: 0  fail: 1

**Comment by fireflycao** [comment]
Collecting unrar
  Downloading unrar-0.3.tar.gz
Installing collected packages: unrar
  Running setup.py install for unrar ... done
Successfully installed unrar-0.3

C:\Users\xxxx>getsub Z:\Media\TV\Narcos.S03.1080p.NF.WEB.DD5.1.x264-NTb[rartv]\Narcos.S03E04.Checkmate.1080p.NF.WEB-DL.DD5.1.x264-NTb.mkv --debug

├ Narcos.S03E04.Checkmate.1080p.NF.WEB-DL.DD5.1.x264-NTb.mkv
├ Z:\Media\TV\Narcos.S03.1080p.NF.WEB.DD5.1.x264-NTb[rartv]
├
├ Get '[ZMZ]Narcos.S03E04.Checkmate.720p.NF.WEB-DL.DD5.1.x264-NTb'...  100.00%
├ error:Unrar not installed?

**Comment by gyh1621** [comment]
不是安装python的unrar。
呃，因为windows下我自己用是没问题的，应该是用了WinRAR带的unrar。
我这两天比较忙，可能看不了，可以尝试添加 `-q` 参数下载同集的其它字幕或者按照rarfile文档里说的下载![RARLAB](http://www.rarlab.com/)里面的unrar并添加路径到PATH试试看。

**Comment by fireflycao** [comment]
WinRAR添加路径到PATH解决问题，win7系统。晚上再试一下win10.
多谢！

**Comment by fireflycao** [comment]
win10也可以了！~作者好棒！

**Comment by gyh1621** [comment]
@lenhoo 可以尝试下 @fireflycao 的方法看看，可以的话我就关issue了。

**Comment by lenhoo** [comment]
“WinRAR添加路径到Path"是将安装目录添加到环境变量吗

**Comment by fireflycao** [comment]
对。安装目录。


发自 Smartisan M1L

Len <notifications@github.com> 于 2017年12月14日 上午9:28写道：


“WinRAR添加路径到Path"是将安装目录添加到环境变量吗

―

**Comment by lenhoo** [comment]
it's done! thx a lot
