### ISSUE TITLE
请更新zimuzu下载地址

### ISSUE THREAD

**Issue by angelsky11** [gyh1621/GetSubtitles#24]
请更新zimuzu地址为最新www.zmz2019.com

另，同样的文件，不加参数下载出错，-s手动选择字幕库就可以下载成功

user@nas# getsub *.mkv --debug

├  Batman.Ninja.2018.1080p.BluRay.x264.DTS-HD.MA.5.1-MT.mkv
├  /volume2/video/movie/Batman.Ninja.2018.1080p.BluRay.x264.DTS-HD.MA.5.1-MT
├ 
├  error:unknown error. try again.

===============================FAILED LIST===============================

 1. name: Batman.Ninja.2018.1080p.BluRay.x264.DTS-HD.MA.5.1-MT.mkv
    path: /volume2/video/movie/Batman.Ninja.2018.1080p.BluRay.x264.DTS-HD.MA.5.1-MT
    info: unknown error. try again.
    TRACE_BACK: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/getsub/main.py", line 592, in start
    downloader.get_subtitles(tuple(keywords))
  File "/usr/lib/python2.7/site-packages/getsub/zimuzu.py", line 46, in get_subtitles
    tab_text = bs_obj.find('div', {'class': 'article-tab'}).text
AttributeError: 'NoneType' object has no attribute 'text'

total: 1  success: 0  fail: 1

**Comment by gyh1621** [comment]
谢谢提醒，已更新。
