### ISSUE TITLE
无法传入环境变量

### ISSUE THREAD

**Issue by ksotin** [gyh1621/GetSubtitles#26]
我设置了 transmission 在下载完成后自动运行如下的 shell 脚本

> #!bin/bash
getsub --plex -o '${TR_TORRENT_DIR}/${TR_TORRENT_NAME}' | cat >> /root/getsub.log

其中 ${TR_TORRENT_DIR} 和 ${TR_TORRENT_NAME} 是 transmission 在下载完成后能够向脚本传送的环境变量。但是 getsub 没有接收到

> The script will replace the old subtitles if exist...
├  ${TR_TORRENT_DIR}/${TR_TORRENT_NAME}
├  /
├ 
├  Searching SUBHD...
├  [SUBHD ERROR] The URI you submitted has disallowed characters: $ NAME 
├  error:'NoneType' object is not iterable. add --debug to get more info of the error
===============================FAILED LIST===============================1. name: ${TR_TORRENT_DIR}/${TR_TORRENT_NAME}
    path: /
    info: 'NoneType' object is not iterable. add --debug to get more info of the error
total: 1  success: 0  fail: 1

**Comment by gyh1621** [comment]
这不是 getsub 的问题。
为什么不自己试试在终端环境下 `getsub --plex -o '${TR_TORRENT_DIR}/${TR_TORRENT_NAME}' | cat >> /root/getsub.log` 这条命令中的`TR_TORRENT_DIR`是否访问到了环境变量呢？

**Comment by ksotin** [comment]
@gyh1621 谢谢回复。那么怎样才能访问到环境变量呢？我试了简单的 Unix 命令都是可以访问到的。我对 Linux 不是太懂，谢谢解答！

**Comment by gyh1621** [comment]
改成 `getsub --plex -o $TR_TORRENT_DIR/$TR_TORRENT_NAME | cat >> /root/getsub.log`试试

**Comment by ksotin** [comment]
@gyh1621 谢谢！这样才是对的
