### ISSUE TITLE
SubHD 获取字幕失败

### ISSUE THREAD

**Issue by ksotin** [gyh1621/GetSubtitles#28]
报错如下：
> info: Expecting value: line 1 column 1 (char 0).

似乎SubHD已经更换域名为subhd.tv，或者网页结构也发生了变化？期待作者更新～

**Comment by gyh1621** [comment]
已更新

**Comment by ksotin** [comment]
@gyh1621 问题似乎仍然存在

**Comment by gyh1621** [comment]
> @gyh1621 问题似乎仍然存在

SubHD上https了，我更新了下链接，升级到1.6.8.7试试

**Comment by ksotin** [comment]
@gyh1621 手动更新了一下，可以了。感谢作者！
