### ISSUE TITLE
不知道能否增加一个下载字幕到指定文件夹的参数

### ISSUE THREAD

**Issue by megaslx** [gyh1621/GetSubtitles#29]
因为平时使用kodi，kodi设置字幕目录的时候比较烦，要么从视频目录读取，要么设置为特定的目录。由于总会有情况脚本或者kodi插件下载不到字幕要自己去网站上下载的情况出现，所以设置为特定目录比较简单，自己下载的时候只需要丢到特定的文件夹就行了（winrar解压缩的时候只要方向键翻到历史记录就行）
我现在手动改了脚本里面的字幕保存目录，但是没去仔细研究代码，所以下载字幕的时候不会判断指定的目录有没有已存在的字幕文件。要是能增加一个参数指定目录就再好不过了，谢谢！

**Comment by gyh1621** [comment]
最近可能没时间添加这个，欢迎发起pr。
处理单个视频有无字幕的代码在[这里](https://github.com/gyh1621/GetSubtitles/blob/master/getsub/main.py#L583)，其中的`video_info`来自[这里](https://github.com/gyh1621/GetSubtitles/blob/master/getsub/main.py#L92-L101)。每个视频字幕的保存目录也是[在`video_info`字典中](https://github.com/gyh1621/GetSubtitles/blob/master/getsub/main.py#L102)。
