### ISSUE TITLE
能问下怎么运行吗？

### ISSUE THREAD

**Issue by fireflycao** [gyh1621/GetSubtitles#3]
unrar.exe闪一下cmd窗口立即消失。

**Comment by gyh1621** [comment]
看readme里的动图，pip安装后打开一个终端输入getsub

2017年12月11日 +0800 PM3:19 fireflycao <notifications@github.com>，写道：

**Comment by gyh1621** [comment]
不好意思 我刚刚邮件里没显示完全
建议通过pip安装 不是通过exe运行的

**Comment by fireflycao** [comment]
没有编程基础，装了python也没弄成，再去学学怎么pip安装。

**Comment by fireflycao** [comment]
D:\xx xx\Python27\Scripts>getsub.exe
Traceback (most recent call last):
  File "D:\Bruce cao\Python27\Scripts\getsub-script.py", line 11, in <module>
    load_entry_point('getsub==1.5.8', 'console_scripts', 'getsub')()
  File "d:\bruce cao\python27\lib\site-packages\pkg_resources\__init__.py", line
 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "d:\bruce cao\python27\lib\site-packages\pkg_resources\__init__.py", line
 2631, in load_entry_point
    return ep.load()
  File "d:\bruce cao\python27\lib\site-packages\pkg_resources\__init__.py", line
 2291, in load
    return self.resolve()
  File "d:\bruce cao\python27\lib\site-packages\pkg_resources\__init__.py", line
 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\Bruce cao\Python27\Scripts\main.py", line 14, in <module>
    import chardet
ImportError: No module named chardet

**Comment by gyh1621** [comment]
pip install chardet

**Comment by fireflycao** [comment]
运行成功，多谢！！！

**Comment by fireflycao** [comment]
还有个问题，怎么能建立一个快捷方式，双击直接进入“D:\xx xx\Python27\Scripts>getsub”

**Comment by gyh1621** [comment]
windows下的话我一般是 win+R 打开cmd，然后输入getsub运行的

**Comment by fireflycao** [comment]
不是有个路径的原因吗？设置环境变量是不是能解决？

**Comment by fireflycao** [comment]
ok了，设置环境变量D:\xx xx\Python27\Scripts。非常感谢。

**Comment by fireflycao** [comment]
-d          选择下载器，现在支持subhd和zimuzu
请问是 -d zimuzu 这样的格式吗？

**Comment by gyh1621** [comment]
没事 😆

**Comment by gyh1621** [comment]
是的

**Comment by fireflycao** [comment]
zumuku。cn 好像也不错，能加上吗？

**Comment by gyh1621** [comment]
这个考虑过，你可以看到有那个分支，但是我后来觉得zimuku的资源subhd和zimuzu都有了，就没继续下去。
