### ISSUE TITLE
建议集成到右键菜单

### ISSUE THREAD

**Issue by tangyao-biu** [gyh1621/GetSubtitles#33]
用命令行输入始终不方便，建议设置注册表将其添加到右键菜单。

**Comment by megaslx** [comment]
可以自己做个批处理，丢到sento目录，然后就可以在“发送到”菜单里面看到了。
内容类似这样：getsub "%1" -p z:\sub --plex

**Comment by gyh1621** [comment]
没有集成右键菜单的计划，可以尝试 @megaslx 的方法手动添加。
