### ISSUE TITLE
subhd.py 字幕字典排序问题

### ISSUE THREAD

**Issue by nitsoh** [gyh1621/GetSubtitles#34]
if (len(sub_dict.items()) > 0
                and list(sub_dict.items())[0][1]['lan'] < 8):
            # 第一个候选字幕没有双语
            sub_dict = order_dict(
                sorted(sub_dict.items(),
                       key=lambda e: e[1]['lan'], reverse=False)
            )

`reverse=False`应当改为`True`使字典按分数降序排列

**Comment by gyh1621** [comment]
谢谢提醒，下个版本改正。
