### ISSUE TITLE
字幕下载错误 &不支持？

### ISSUE THREAD

**Issue by malagebidi** [gyh1621/GetSubtitles#35]
> ├  Fast.&.Furious.Presents.Hobbs.&.Shaw.2019.1080p.WEBRip.x264-[YTS.LT].mp4
├  /volumeUSB1/usbshare/Video/Fast & Furious Presents Hobbs & Shaw (2019) [WEBRip] [1080p] [YTS.LT]
├ 
├  [SUBHD ERROR] The URI you submitted has disallowed characters: Fast & Furious Presents Hobbs & Shaw YTS.LT 1080p 
├  error:'NoneType' object is not iterable. add --debug to get more info of the error

**Comment by gyh1621** [comment]
subhd的搜索不支持`&`，我下个版本过滤一下，麻烦现在手动去掉`&`字符。
