### ISSUE TITLE
源网站是否可以跟新下？

### ISSUE THREAD

**Issue by fireflycao** [gyh1621/GetSubtitles#4]
zimuzu最近新电影好多没有，subhd下载3，4个就被封一段时间。
zimuku.cn还可以，建议加上去，多谢！

**Comment by gyh1621** [comment]
电影用subhd下一次三四个电影还不够吗  😓  哪些电影在zimuzu搜不到呢 我看下是不是关键字的问题

**Comment by gyh1621** [comment]
@fireflycao zimuku主要是搜索结果页面不固定的问题，一些关键字搜出来是合集，一些搜出来是单个字幕。只能等我有时间了再做了。

**Comment by fireflycao** [comment]
比如black.mirror.s04，一起下了6集，图省事一起拖进去，zimuzu没有，subhd暂时下不了。

**Comment by fireflycao** [comment]
下载电影在nas，几个人访问，所以经常是有空时想一下把字幕搞定，然后就被subhd搞定了！  :sweat: 
![capture111](https://user-images.githubusercontent.com/20470524/34452182-acb84d52-ed74-11e7-9090-c1bf6cd2b399.JPG)

**Comment by gyh1621** [comment]
@fireflycao 我看了下，黑镜第四季有几集在字幕组上几个小时前更新了字幕，你现在下应该会有字幕了。SubHD上的黑镜第四季那几集字幕也是和字幕组同步更新的。你那时下在字幕组没资源可能是还没上传字幕。
电影字幕的确是SubHD和字幕库丰富一点，但是如上所说，字幕库有点麻烦，可能要等我有时间了才能添加进去 😅

**Comment by fireflycao** [comment]
多谢！～

**Comment by gyh1621** [comment]
没事。我保持这个Issue开着，完成了通知你。

**Comment by gyh1621** [comment]
已经加入了字幕组的下载器，更新下试试 :relieved:
