### ISSUE TITLE
在-q时候能否再多给点选择？

### ISSUE THREAD

**Issue by lvcha2** [gyh1621/GetSubtitles#43]
有时候挺好匹配的片子因为有美剧之类的造成选择过多以至于正确的选项不在前五个。
或者匹配条件再考虑一下？kodi里的shooter插件匹配的就挺准确？

├  Fury.2014.2160p.UHD.BluRay.x265-TERMiNAL.mkv
├    1)       【繁】              [SUBHD]阴曹使者.The.Divine.Fury.2019.1080p.FHDRip.H264.AAC-MreD
├    2) 【简】                    [SUBHD]【使者 The.Divine.Fury】2019.特效字幕.FHDRip.FIX字幕侠
├    3) 【简】                    [SUBHD]精武门 Fist.of.Fury.1972
├    4) 【简】【繁】              [SUBHD]铁拳第2季第1集Marvels.Iron.Fist.S02E01.The.Fury.of.the.Iron.Fist.1080p.NF.WEB-DL.DDP5.1.x264-NTG
├    5) 【简】【繁】【英】【双】  [SUBHD]【闪电侠 The.Flash】S04E19.中英特效双语字幕.WEBDL.FIX字幕侠

**Comment by lvcha2** [comment]
或者-q时候能够自己输入关键字再查找？
这种修改可能略复杂

**Comment by wangning8848** [comment]
我也觉得5个选项太少了，有的时候5个都不对或者都不是自己想要的。既然决定手动了是不是应该多提供点选择？谢谢

**Comment by gyh1621** [comment]
现在搜索不会添加年份，电影的后续我会加上年份进行匹配。

可以用`-n 10`设置候选数。

**Comment by gyh1621** [comment]
已加强对电影的搜索，现在使用 subhd 和 zimuzu 下载电影字幕会过滤电视剧的字幕，可以更新尝试下。
