### ISSUE TITLE
新版本的安装要求有点高

### ISSUE THREAD

**Issue by megaslx** [gyh1621/GetSubtitles#45]
新引入的pylzma模块需要Microsoft Visual C++ Build Tools，否则直接pip install安装会报错的。7z难道unrar不能胜任么？

**Comment by megaslx** [comment]
我跑去https://www.lfd.uci.edu/~gohlke/pythonlibs/ 找到了pylzma的whl文件才免于装那个几个G大的build tools

**Comment by gyh1621** [comment]
unrar解压不了7z。

这次在windows上测试的时候，可能上面本来就装着那些依赖了，所以安装新版本的时候没有提示要装额外依赖，不好意思。

这样的话windows上装确实比较麻烦，我再找找有没有其它库能解压7z的。现在我先在Readme里提示下吧。

**Comment by megaslx** [comment]
有一个叫py7zr的模块好像可以读写7z，不知道能不能满足需求，个人测试了一下可以直接装上不需要build tools

**Comment by gyh1621** [comment]
谢谢提醒。不过我去看了下py7zr要求最低Python 3.5的版本，这样Python 2就用不了了。

**Comment by gyh1621** [comment]
因为要同时兼容Python2和3，满足条件的解压7z的库除了pylzma，都需要调用额外安装的7z程序。如果电脑上本来没有安装7z，可能还是直接安装pylzma的whl文件来得方便，我觉得目前还是继续使用pylzma吧。
