### ISSUE TITLE
Incompatible pylzma version on ARM64

### ISSUE THREAD

**Issue by simsicon** [gyh1621/GetSubtitles#46]
Related issue: https://github.com/fancycode/pylzma/issues/73
Not sure if this issue was introduced by ARM platform, but I cant not meet the pylzma==0.5.0 requirement, maybe please try to change it to "pylzma>=0.5.0"?

Thanks for your work

**Comment by gyh1621** [comment]
Hi, I don't have ARM platform but I get the same result on macOS with Python 3.6.0. I have changed the requirement to "pylzma>=0.5.0" and it works now. Please install the latest version of getsub (1.7.1). Sorry for the inconvenience.
