### ISSUE TITLE
請問是否可以新增其他選項?

### ISSUE THREAD

**Issue by kuenming** [gyh1621/GetSubtitles#5]
如 
1.只下載繁體 或 繁體英文雙語字幕
2.轉換字幕格式可選擇 成其他格式:如Big5

**Comment by gyh1621** [comment]
没有这方面的改进计划，现在可以用纯手动模式 -q -s 选择到单字幕，以后可能会考虑加入在自动模式下选择优先语言的选项（现在是优先简英双语）。
Big5不是一种字符编码吗？我没在字幕格式里看到这种格式。

**Comment by kuenming** [comment]
明白了

**Comment by gyh1621** [comment]
抱歉，应该不会做这个功能了。
