### ISSUE TITLE
建议增加选项“指定搜索关键字”

### ISSUE THREAD

**Issue by kSotin** [gyh1621/GetSubtitles#50]
搭配 radarr, sonarr 等使用时，经常会对文件进行重新命名整理。这种情况下，如果能够使用原始文件名进行搜索，可以提高字幕匹配的成功率和精确度。

**Comment by gyh1621** [comment]
记下了，不过可能不会很快实现... 之前还有很多东西我没改完

**Comment by gyh1621** [comment]
使用原始文件名搜索是指不拆分关键字直接搜索整个文件名吗？我觉得这样的效果可能不会很好。

**Comment by kSotin** [comment]
谢谢关注。我是指指定一个字符串代替文件名进行搜索，因为在有些情况下文件名会被更改。拆分还是按照正常规则拆分
