### ISSUE TITLE
subhd改版了。。。

### ISSUE THREAD

**Issue by megaslx** [gyh1621/GetSubtitles#52]
初看了一下改动还蛮大的，我对html不熟悉，只能一段段代码放到新的网站数据里面去看。要等大佬来修了

**Comment by megaslx** [comment]
我自己修改了一部分代码后可以拿到下载页面的地址了，但是最有一步下载有点扯，就算了浏览器里手工点也有50%的概率会让你刷新页面后重试，有点类似改版前，搜索关键字的时候经常需要重试一样，这一步用python好像下了几次都没成功下下来，不知道有什么窍门，我看了post请求好像结构没有变化

**Comment by gyh1621** [comment]
我看了下只是搜索结果页面的网页结构改了，我这边测试下一会应该就能更新了

**Comment by gyh1621** [comment]
更新了，升级下吧
