### ISSUE TITLE
群晖无法安装新版

### ISSUE THREAD

**Issue by angelsky11** [gyh1621/GetSubtitles#53]
1.7.0.0版本以后需要pylzma>=0.5.0
但是群晖系统是装不上这个的
请问这个是必须依赖么？

**Comment by gyh1621** [comment]
暂时是必须依赖，后面计划改成选装的。

**Comment by angelsky11** [comment]
> 暂时是必须依赖，后面计划改成选装的。

那还是暂时使用1.6.9.0了，请问新版除了变更下载网站地址外还有什么改进么？

**Comment by gyh1621** [comment]
1.6.9.0有几个bug修复了，同时优化了下电影的搜索结果。
我看到forks里有人把pylzma去掉了，你可以试试这个分支：https://github.com/seiry/GetSubtitles

**Comment by bread22** [comment]
这个不能在群晖上用就可惜了，可以用`pyunpack` + `patool` 来替换 `pylzma`。
我试过可以，就是不能解压前读文件名。可以先解压到`tmp`，重新封装一下，还用`Py7z`的API

**Comment by angelsky11** [comment]
> 这个不能在群晖上用就可惜了，可以用`pyunpack` + `patool` 来替换 `pylzma`。
> 我试过可以，就是不能解压前读文件名。可以先解压到`tmp`，重新封装一下，还用`Py7z`的API

**Comment by bread22** [comment]
看了一下，没我想的那么简单，传过来的是archive data，不是archive file name。。。

**Comment by gyh1621** [comment]
> 看了一下，没我想的那么简单，传过来的是archive data，不是archive file name。。。

按你说的先全部解压不行吗？

**Comment by bread22** [comment]
@gyh1621 原本的设计是递归拿handler，全解压递归好像就出问题

**Comment by gyh1621** [comment]
> @gyh1621 原本的设计是递归拿handler，全解压递归好像就出问题

啊也是，如果将解压抽象成一个类，那后面继承的子类可以重载拿全部文件的方法，这样应该可以集成进去。

**Comment by bread22** [comment]
我在想最简单的办法应该是碰到7z，就解压再压成zip，交给zip去处理。这样比较难看，而且程序会比较慢，虽然也慢不到哪里去。我再想想

**Comment by gyh1621** [comment]
@angelsky11 @bread22  `.7z` 的解压换成了用外部的 7z 程序处理，二位有时间麻烦看看。最新的版本只支持 Python 3 了。
