### ISSUE TITLE
error:'content-length' from zimuzu

### ISSUE THREAD

**Issue by kuenming** [gyh1621/GetSubtitles#6]
下载器選 zimuzu 會出現此錯誤,選 subhd 正常
getsub B:\The.Flash.2014.S04E10.720p.HDTV.x264-AVS.mkv -d zimuzu

├ The.Flash.2014.S04E10.720p.HDTV.x264-AVS.mkv
├ B:\
├
├ error:'content-length'. add --debug to get more info of the error

===============================FAILED LIST===============================

 1. name: The.Flash.2014.S04E10.720p.HDTV.x264-AVS.mkv
    path: B:\
    info: 'content-length'. add --debug to get more info of the error

total: 1  success: 0  fail: 1

**Comment by kuenming** [comment]
getsub B:\The.Flash.2014.S04E10.720p.HDTV.x264-AVS.mkv -d zimuzu --debug

├ The.Flash.2014.S04E10.720p.HDTV.x264-AVS.mkv
├ B:\
├
├ error:'content-length'.

===============================FAILED LIST===============================

 1. name: The.Flash.2014.S04E10.720p.HDTV.x264-AVS.mkv
    path: B:\
    info: 'content-length'.
    TRACE_BACK: Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\main.py", line 467, in start
    sub_choice, link
  File "c:\python36-32\lib\site-packages\zimuzu.py", line 97, in download_file
    content_size = int(response.headers['content-length'])
  File "c:\python36-32\lib\site-packages\requests\structures.py", line 54, in __
getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'


total: 1  success: 0  fail: 1

**Comment by gyh1621** [comment]
字幕组下载页面变了，已更新，麻烦用pip升级下。
