### ISSUE TITLE
ZIMUZU的下载出现错误。

### ISSUE THREAD

**Issue by Genion** [gyh1621/GetSubtitles#69]
0) Exit. Not downloading any subtitles.
  1) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶 第一季第十二集【WEB-DL】》(Intelligence S01E12)
  2) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶第一季第十二集【HDTV】》(Intelligence S01E12)
  3) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶 第一季第十三集【WEB-DL】》(Intelligence S01E13)
  4) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶第一季第十一集【WEB-DL】》(IntelligenceS01E11)
  5) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶第一季第十集【WEB-DL】》(IntelligenceS01E10)

 choose: 1

error:Expecting value: line 1 column 1 (char 0)
  0) Exit. Not downloading any subtitles.
  1) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶第一季第十二集【HDTV】》(Intelligence S01E12)
  2) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶 第一季第十三集【WEB-DL】》(Intelligence S01E13)
  3) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶第一季第十一集【WEB-DL】》(IntelligenceS01E11)
  4) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶第一季第十集【WEB-DL】》(IntelligenceS01E10)

 choose: 1

error:Expecting value: line 1 column 1 (char 0)
  0) Exit. Not downloading any subtitles.
  1) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶 第一季第十三集【WEB-DL】》(Intelligence S01E13)
  2) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶第一季第十一集【WEB-DL】》(IntelligenceS01E11)
  3) 【简】【繁】【英】【双】  [ZIMUZU][美剧字幕]《智能缉凶第一季第十集【WEB-DL】》(IntelligenceS01E10)

出现这种错误怎么办？Windows10 Python 3.8.2

**Comment by gyh1621** [comment]
已修复，请更新到 1.7.8
