### ISSUE TITLE
zimuku似乎没成功搜索到字幕？

### ISSUE THREAD

**Issue by fireflycao** [gyh1621/GetSubtitles#7]
网页有，软件显示没搜

![capture](https://user-images.githubusercontent.com/20470524/35426690-d804cf40-029f-11e8-9ee5-3cb9e149abc9.JPG)

**Comment by gyh1621** [comment]
不好意思，这个是因为字幕的名字里面没有包含 "Gangster Land" 这个英文名而导致被过滤掉了。之前没看到"又名"这个部分写的时候没考虑，我现在加一下。

**Comment by gyh1621** [comment]
已上传，麻烦更新下

**Comment by gyh1621** [comment]
因为字幕库搜索结果有时候有点乱，所以自动模式下可能不会是双语优先
