### ISSUE TITLE
error: zimuku downloader needs updates

### ISSUE THREAD

**Issue by benwwchen** [gyh1621/GetSubtitles#72]
```
getsub -q -b --plex somemovie.mkv --debug -d zimuku

- Video: somemovie
- Video Path: /...
- Subtitles Store Path: /...

error: zimuku downloader needs updates
ERROR:no search results.

===============================FAILED LIST===============================

 1. name: somemovie
    path: /..
    info: no search results.
    TRACE_BACK:

total: 1  success: 0  fail: 1
```

**Comment by gyh1621** [comment]
please update to 1.7.9

**Comment by wei134102** [comment]
(base) root@b4b65c1b3c36:/mnt/user/downloads/share# getsub -q -d zimuzu --debug 'The.Stand.2020.S01E05.XviD-AFG[eztv.re].avi'

- Video: The.Stand.2020.S01E05.Fear.and.Loathing.in.New.Vegas.720p.AMZN.WEB-DL.DDP5.1.H.264-NTG
- Video Path: /mnt/user/downloads/share/The.Stand.2020.S01E05.XviD-AFG[eztv.re].avi
- Subtitles Store Path: /mnt/user/downloads/share/The.Stand.2020.S01E05.XviD-AFG[eztv.re].avi

  0) Exit. Not downloading any subtitles.
  1) 【简】【繁】【英】【双】  [ZIMUZU][欧美剧字幕]《末日逼近 第1季第5集》(The Stand S01E05)
  2) 【简】【繁】【英】【双】  [ZIMUZU][欧美剧字幕]《末日逼近 第1季第6集》(The Stand S01E06)
  3) 【简】【繁】【英】【双】  [ZIMUZU][欧美剧字幕]《末日逼近 第1季第4集》(The Stand S01E04)
  4) 【简】【繁】【英】【双】  [ZIMUZU][欧美剧字幕]《末日逼近 第1季第3集》(The Stand S01E03)
  5) 【简】【繁】【英】【双】  [ZIMUZU][欧美剧字幕]《末日逼近 第1季第2集》(The Stand S01E02)

 choose: 1

error:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
  0) Exit. Not downloading any subtitles.
  1) 【简】【繁】【英】【双】  [ZIMUZU][欧美剧字幕]《末日逼近 第1季第6集》(The Stand S01E06)
  2) 【简】【繁】【英】【双】  [ZIMUZU][欧美剧字幕]《末日逼近 第1季第4集》(The Stand S01E04)
  3) 【简】【繁】【英】【双】  [ZIMUZU][欧美剧字幕]《末日逼近 第1季第3集》(The Stand S01E03)
  4) 【简】【繁】【英】【双】  [ZIMUZU][欧美剧字幕]《末日逼近 第1季第2集》(The Stand S01E02)

 choose: 0

ERROR: failed to guess one subtitle,use '-q' to try query mode.
