### ISSUE TITLE
字幕下载失败&空字幕文件Bug 附运行日志

### ISSUE THREAD

**Issue by 821938089** [gyh1621/GetSubtitles#75]
getsub执行完成后会在电影目录下留下一个空的字幕文件。
字幕下完提示error:Cannot find working tool，不知道是什么错误。

以下为日志（部分路径已打码）：
getsub "U:\...\Kuffs.1992\Kuffs.1992.1080p.BluRay.REMUX.AVC.DTS-HD.MA.2.0-FGT.mkv" --debug

- Video: Kuffs.1992.1080p.BluRay.REMUX.AVC.DTS-HD.MA.2.0-FGT
- Video Path: U:\...\Kuffs.1992
- Subtitles Store Path: U:\...\Kuffs.1992

Get '[ZIMUKU]Kuffs.1992.WS.DVDRip.XviD-VoMiT.Subrip.chs.cht.eng-NewMov'...  100.00%
error:Cannot find working tool
Get '[ZIMUKU]_Kuffs_1992_XviD_AC3_2CD_WAF'...  100.00%
error:Cannot find working tool
Get '[ZIMUKU][我的子弹会转弯].Kuffs.1992.XviD.AC3.2CD-WAF'...  100.00%
error:Cannot find working tool
ERROR: failed to guess one subtitle,use '-q' to try query mode.

===============================FAILED LIST===============================

 1. name: Kuffs.1992.1080p.BluRay.REMUX.AVC.DTS-HD.MA.2.0-FGT
    path: U:\...\Kuffs.1992
    info:  failed to guess one subtitle,use '-q' to try query mode.
    TRACE_BACK:

total: 1  success: 0  fail: 1

**Comment by gyh1621** [comment]
这应该是`rarfile`库报的错误，请检查下有没有下载`unrar`并放入系统路径。

**Comment by 821938089** [comment]
弄好了，是我环境变量弄错了，我直接新建了一个变量来放路径。

正确应该是修改Path变量，在这个变量里添加解压程序的文件夹路径。

建议改下Readme说一下把解压程序放到哪里（具体路径）。
