### ISSUE TITLE
能否做一个kodi版本的插件呢

### ISSUE THREAD

**Issue by monokoo** [gyh1621/GetSubtitles#8]
能否做一个kodi版本的插件呢，使用kodi自动下载方便点，谢谢

**Comment by gyh1621** [comment]
不好意思，我不用kodi，所以应该不会做这方面的插件了

**Comment by monokoo** [comment]
东西应该都差不多，只是不懂py。这是kodi版本的https://github.com/taxigps/xbmc-addons-chinese/tree/master/service.subtitles.subhd，好久没更新了

**Comment by gyh1621** [comment]
建议在那边开个issue要求更新下，我这边没有kodi也没法测试
