### ISSUE TITLE
某些字幕下载失败

### ISSUE THREAD

**Issue by sokouu** [gyh1621/GetSubtitles#9]
某些字幕下载失败，并在文件夹下建立了一个0字节的字幕文件，尝试用debug模式，显示如下log：

shaogongyudeiMac:~ shaogongyu$ getsub /Volumes/视频/Shameless.US.S08E12.1080p.WEB.H264-DEFLATE[rarbg]/Shameless.US.S08E12.1080p.WEB.H264-DEFLATE.mkv --debug

├ Shameless.US.S08E12.1080p.WEB.H264-DEFLATE.mkv
├ /Volumes/视频/Shameless.US.S08E12.1080p.WEB.H264-DEFLATE[rarbg]
├
├ Get '[ZMZ]Shameless.US.S08E12.Sleepwalking...'...  100.00%
├ error:Failed the read enough data. 

===============================FAILED LIST===============================

 1. name: Shameless.US.S08E12.1080p.WEB.H264-DEFLATE.mkv
    path: /Volumes/视频/Shameless.US.S08E12.1080p.WEB.H264-DEFLATE[rarbg]
    info: Failed the read enough data. 
    TRACE_BACK: Traceback (most recent call last):
  File "/Users/shaogongyu/anaconda3/lib/python3.6/site-packages/main.py", line 496, in start
    sub_data_bytes, info_dict, self.single
  File "/Users/shaogongyu/anaconda3/lib/python3.6/site-packages/main.py", line 406, in extract_subtitle
    sub.write(file_handler.read(sub_name))
  File "/Users/shaogongyu/anaconda3/lib/python3.6/site-packages/rarfile.py", line 772, in read
    return f.read()
  File "/Users/shaogongyu/anaconda3/lib/python3.6/site-packages/rarfile.py", line 2010, in read
    raise BadRarFile("Failed the read enough data")
rarfile.BadRarFile: Failed the read enough data

total: 1  success: 0  fail: 1

**Comment by sokouu** [comment]
https://github.com/Diaoul/subliminal/issues/709

是unrar的问题，供参考。

**Comment by gyh1621** [comment]
看起来是unrar版本的问题，我在 ubuntu 16.04 下用  `sudo apt install unrar`  安装的 unrar 下载你上面的字幕没有报错，下个版本加入检查到这个错误就跳过该字幕。
[BadRarFile: Failed the read enough data](https://github.com/markokr/rarfile/issues/10)
[BadRarFile: Failed the read enough data](https://github.com/markokr/rarfile/issues/14)
Shameless 是我最喜欢的剧之一了，抱歉回复晚了 :sweat_smile:

**Comment by sokouu** [comment]
插件很好用,但好像没推广,搜了好久才进来😄

**Comment by gyh1621** [comment]
恩，就最开始在 v2 和 [HelloGitHub](https://github.com/521xueweihan/HelloGitHub) 那里宣传过，后面觉得代码写得太烂了又简单就不好意思说了，好用就行，hh

**Comment by gyh1621** [comment]
我加了一个检查，但是因为我这里复现不了这个错误，希望有用吧 :smiling_imp:
